# -*- coding: utf-8 -*-
"""intent_classifier.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zDt-r-ypu5Wn-a2iNWkUvCMDMIfX69H
"""

from typing import Dict
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from loguru import logger
from config import model_config

# Handles intent classification using a transformer model.
class IntentClassifier:
  def __init__(self):
    self.model_name = model_config.INTENT_MODEL
    self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
    self.model = AutoModelForSequenceClassification.from_pretrained(self.model_name)

  # Predict intent of input text. It returns the Label and Confidence Score
  def predict(self, text: str) -> Dict:
    try:
      # Tokenize input text (convert to model input format)
      inputs = self.tokenizer(text, return_tensors="pt", truncation=True)
      # Run model inference
      outputs = self.model(**inputs)
      # Convert inputs to probabilities
      probs = torch.nn.functional.softmax(outputs.logits, dim = 1)
      # Get highest probability class
      confidence, predicted_class = torch.max(probs, dim=1)

      return {
          "label": int(predicted_class.item()),
          "confidence": float(confidence.item())
      }

    except Exception as e:
      logger.error(f"Intent classification error: {e}")
      return {"label": None, "confidence": 0}