# -*- coding: utf-8 -*-
"""language_detector.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTmoThGBumEQOOiAC5xH6DgUxJWB17Ss
"""

from typing import Dict
from loguru import logger
from langdetect import detect

# Detect language of input text.
def detect_language(text: str) -> Dict:
  try:
    # Detect language using langdetect
    lang = detect(text)
    return {"language": lang}

  except Exception as e:
    logger.error(f"Language detection error: {e}")
    return {"language": "unknown"}