# -*- coding: utf-8 -*-
"""sentiment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8_VcDYgh_tjjTZGuwp2soNaLNg58Ih4
"""

from typing import Dict
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from loguru import logger
from config import model_config

# Performs sentiment analysis on input text
class SentimentAnalyzer:
  def __init__(self):
    self.model_name = model_config.SENTIMENT_MODEL
    self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
    self.model = AutoModelForSequenceClassification.from_pretrained(self.model_name)

  # Analyze sentiment of text.
  def analyze(self, text: str) -> Dict:
    try:
      # Tokenize the input text
      inputs = self.tokenizer(text, return_tensors="pt", truncation=True)
      # Run model inference
      outputs = self.model(**inputs)
      # Convert logits into probabilities
      probs = torch.nn.functional.softmax(outputs.logits, dim = -1)
      # Get highest probability class
      confidence, predicted_class = torch.max(probs, dim = 1)

      return {
          "label": int(predicted_class.item()),
          "confidence": float(confidence.item())
      }

    except Exception as e:
      logger.error(f"Sentiment error: {e}")
      return {"label":None, "confidence": 0}